// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "WTFPL",
            "url": "https://github.com/mohemohe/parakeet/blob/master/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "アクセストークンが有効か判定します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    }
                }
            },
            "post": {
                "description": "メールアドレスとパスワードを送信してアクセストークンを取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.AuthResponse"
                        }
                    }
                }
            }
        },
        "/v1/entries": {
            "get": {
                "description": "エントリー一覧を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "list entries",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "ページネーションのページ数",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "1ページごとの件数",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Entries"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "エントリーを作成します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "create entry",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Entry"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.EntryResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    }
                }
            }
        },
        "/v1/entries/{id}": {
            "get": {
                "description": "エントリー一覧を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "get entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "エントリーの 'Mongo ObjectID'",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.EntryResponse"
                        }
                    },
                    "404": {}
                }
            },
            "put": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "エントリーを更新します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "update entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "エントリーの 'Mongo ObjectID'",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Body",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Entry"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.EntryResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    },
                    "404": {}
                }
            },
            "delete": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "エントリーを削除します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "delete entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "エントリーの 'Mongo ObjectID'",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    },
                    "404": {}
                }
            }
        },
        "/v1/settings/cache/cloudflare": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Cloudflareのキャッシュ削除設定を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "get Cloudflare purge info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Cloudflareのキャッシュ削除設定を更新します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "set Cloudflare purge info",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Cloudflare"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    }
                }
            }
        },
        "/v1/settings/cache/mongodb": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "MongoDB クエリーのキャッシュ設定を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "get MongoDB query cache",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "MongoDB クエリーのキャッシュ設定を更新します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "set MongoDB query cache",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    }
                }
            }
        },
        "/v1/settings/cache/page": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "サーバーサイドレンダリングで生成したHTMLのキャッシュ設定を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "get SSR-ed page cache",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "サーバーサイドレンダリングで生成したHTMLのキャッシュ設定を更新します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "set SSR-ed page cache",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    }
                }
            }
        },
        "/v1/settings/notify/mastodon": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Mastodonの通知設定を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "get mastodon notification",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "Mastodonの通知設定を更新します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "set mastodon notification",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.NotifyMastodon"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    }
                }
            }
        },
        "/v1/settings/render/server": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "サーバーサイドレンダリングの設定を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "get SSR",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "サーバーサイドレンダリングの設定を更新します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "set SSR",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ServerSideRendering"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    }
                }
            }
        },
        "/v1/settings/site/sidenav": {
            "get": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "サイドバー コンテンツの設定を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "get side nav contents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "サイドバー コンテンツの設定を更新します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "set side nav contents",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    }
                }
            }
        },
        "/v1/settings/site/title": {
            "get": {
                "description": "サイト名を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "get site title",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AccessToken": []
                    }
                ],
                "description": "サイト名を設定します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "setting"
                ],
                "summary": "set site title",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.Setting"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KV"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.EmptyJson"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.AuthRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "controllers.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "type": "object",
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "controllers.EntryResponse": {
            "type": "object",
            "properties": {
                "entry": {
                    "type": "object",
                    "$ref": "#/definitions/models.Entry"
                }
            }
        },
        "controllers.Setting": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "object"
                }
            }
        },
        "middlewares.EmptyJson": {
            "type": "object"
        },
        "models.Cloudflare": {
            "type": "object",
            "properties": {
                "api_token": {
                    "type": "string"
                },
                "enable": {
                    "type": "boolean"
                },
                "zone_id": {
                    "type": "string"
                }
            }
        },
        "models.Entries": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Entry"
                    }
                },
                "info": {
                    "type": "string"
                }
            }
        },
        "models.Entry": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                },
                "draft": {
                    "type": "boolean"
                },
                "tag": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.KV": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "object"
                }
            }
        },
        "models.NotifyMastodon": {
            "type": "object",
            "properties": {
                "baseurl": {
                    "type": "string"
                },
                "template": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "models.ServerSideRendering": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "boolean"
                },
                "entry": {
                    "type": "boolean"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "AccessToken": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0 Draft",
	Host:        "",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "parakeet REST API",
	Description: "### Fast weblog built in golang and top of echo. supports React SSR and hydrate.\nlabstack/echoを使った高速なブログエンジン。\nReactのサーバーサイドレンダリングとクライアントサイドの引き継ぎを実装。\n（ぶっちゃけ速いかと言われるとSSR有効時はそうでもない）",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
