name: build

on:
  push:
    branches:
      - master
      - edge
    tags:
      - v*.*.*

jobs:
  build_client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: ./client/yarn.lock

      - run: yarn config set network-timeout 120000

      - run: yarn install --frozen-lockfile
        working-directory: client

      - run: yarn build
        working-directory: client

      - uses: actions/upload-artifact@v3
        with:
          name: client
          path: server/public

  build_docker_image:
    needs: build_client

    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          name: client
          path: server/public

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: mohemohe/parakeet
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - uses: docker/build-push-action@v3
        with:
          platforms: ${{ matrix.arch }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=${{ matrix.arch }}

  update_dockerhub_readme:
    needs: build_docker_image

    runs-on: ubuntu-latest

    steps:
      - uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: mohemohe/parakeet
          readme-filepath: ./README.md
          short-description: Fast weblog built in golang and top of echo. Supports React SSR and hydrate.
