name: build

on:
  push:
    branches:
      - master
      - edge
    tags:
      - v*.*.*

concurrency:
  group: build-${{ github.ref }}

jobs:
  build_client:
    runs-on: buildjet-4vcpu-ubuntu-2204

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: ./client/yarn.lock

      - run: yarn config set network-timeout 120000

      - run: yarn install --frozen-lockfile
        working-directory: client

      - run: yarn build
        working-directory: client

      - uses: actions/upload-artifact@v3
        with:
          name: client
          path: server/public

  fetch_docker_metadata:
    needs: build_client

    runs-on: buildjet-2vcpu-ubuntu-2204

    outputs:
      tags: ${{ steps.tags.outputs.tags }}
      labels: ${{ steps.labels.outputs.labels }}
    steps:
      - uses: docker/login-action@v2
        with:
          username: mohemohe
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: mohemohe/parakeet
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - id: tags
        run: echo "tags=${{ steps.metadata.outputs.tags }}" >> $GITHUB_OUTPUT

      - id: labels
        run: echo "labels=${{ steps.metadata.outputs.labels }}" >> $GITHUB_OUTPUT

  build_docker_image_amd64:
    needs: fetch_docker_metadata

    runs-on: buildjet-4vcpu-ubuntu-2204

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          name: client
          path: server/public

      - uses: docker/login-action@v2
        with:
          username: mohemohe
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          platforms: linux/amd64
          tags: ${{ needs.fetch_docker_metadata.outputs.tags }}
          labels: ${{ needs.fetch_docker_metadata.outputs.labels }}

  build_docker_image_arm64:
    needs: fetch_docker_metadata

    runs-on: buildjet-4vcpu-ubuntu-2204-arm

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          name: client
          path: server/public

      - uses: docker/login-action@v2
        with:
          username: mohemohe
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          platforms: linux/arm64
          tags: ${{ needs.fetch_docker_metadata.outputs.tags }}-arm64
          labels: ${{ needs.fetch_docker_metadata.outputs.labels }}

  update_dockerhub_readme:
    needs:
      - build_docker_image_amd64
      - build_docker_image_arm64

    runs-on: buildjet-2vcpu-ubuntu-2204

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: peter-evans/dockerhub-description@v3
        with:
          username: mohemohe
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: mohemohe/parakeet
          short-description: Fast weblog built in golang and top of echo. Supports React SSR and hydrate.
